server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          # Git仓库地址
          uri: https://github.com/aesopcmc/spring-cloud-config-serve.git
          # Git仓库账号
          username:
          # Git仓库密码
          password:
# 启动后，直接访问测试http://localhost:8080/microservice-foo-dev.yml
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG