server:
  # 指定Tomcat端口
  port: 8030
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-consumer-movie
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.130:8848
  jpa:
    # 让hibernate打印执行的SQL
    show-sql: true
logging:
  level:
    root: INFO
    # 配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

#监控应用运行状况 http://{ip}:{port}/actuator/{endpoint}
#健康检查 http://{ip}:{port}/actuator/health
#熔断信息 http://{ip}:{port}/actuator/hystrix.stream
management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
  endpoints:
    web:
      exposure:
        #'hystrix.stream'
        include: '*'
