server:
  port: 8050
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://user:123123@peer1:8761/eureka/,http://user:123123@peer2:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 自定义指定微服务的访问路径
zuul:
  # ignored-services:
  routes:
    microservice-consumer-movie-feign: /movie/** #使用例子http://localhost:8050/movie/movies/users/2

logging:
  level:
    com.netflix: DEBUG

##集群配置，只需要按照不同的端口启动即可
#---
#server:
#  port: 8051
#spring:
#  profiles: zuul1
#---
#server:
#  port: 8052
#spring:
#  profiles: zuul2
